"""Corporate black & emerald theme for the CrudeWatch app."""
from theme.palette import (
    ACCENT,
    ACCENT_MUTED,
    AMBER,
    BACKGROUND,
    BEAR,
    BORDER,
    BULL,
    FLAT,
    SUBTEXT,
    SURFACE,
    TEXT,
    inject_css,
    nav_label,
    phase_note,
    sidebar_brand,
    sidebar_card,
    sidebar_footer,
    signal_chip,
    title_block,
)

__all__ = [
    "ACCENT",
    "ACCENT_MUTED",
    "AMBER",
    "BACKGROUND",
    "BEAR",
    "BORDER",
    "BULL",
    "FLAT",
    "SURFACE",
    "TEXT",
    "SUBTEXT",
    "inject_css",
    "nav_label",
    "phase_note",
    "sidebar_brand",
    "sidebar_card",
    "sidebar_footer",
    "signal_chip",
    "title_block",
]
